# -*- coding: utf-8 -*-
"""Sustainable Smart City Assistance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g5YGKvuxp4mqIVc7pCx6hzARBhenQTue
"""

!pip install transformers torch gradio PyPDF2 -q

import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# Load model and tokenizer
model_name = "ibm-granite/granite-3.2-2b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto" if torch.cuda.is_available() else None
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def generate_response(prompt, max_length=1024):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)

    if torch.cuda.is_available():
        inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_length=max_length,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    response = response.replace(prompt, "").strip()
    return response

def disease_prediction(symptoms):
    prompt = f"Based on the following symptoms: {symptoms}, provide possible medical conditions and general recommendations. Please note that this is not a substitute for professional medical advice."
    return generate_response(prompt, max_length=1000)

def extract_text_from_pdf(pdf_file):
    try:
        pdf_reader = PyPDF2.PdfReader(pdf_file)
        text = ""
        for page in pdf_reader.pages:
            text += page.extract_text() + "\n"
        return text
    except Exception as e:
        return f"Error reading PDF: {str(e)}"

def policy_summarization(pdf_file, medical_condition):
    # Get text from PDF or direct input
    if pdf_file is not None:
        content = extract_text_from_pdf(pdf_file)
        summary_prompt = f"Summarize the following policy document and extract the most important points, key provisions, and implications:\n\n{content}"
    else:
        summary_prompt = f"Generate a personalized treatment plan for a patient with {medical_condition}. Please note that this is not a substitute for professional medical advice."

    return generate_response(summary_prompt, max_length=1200)

# Create Gradio interface
with gr.Blocks() as app:
    gr.Markdown("# Medical AI assistant")

    with gr.Tabs():
        with gr.TabItem("Disease prediction"):
            with gr.Row():
                with gr.Column():
                    keywords_input = gr.Textbox(
                        label="Enter symptoms",
                        placeholder="e.g., fever,headache,cough,fatique...",
                        lines=3
                    )
                    predict_btn = gr.Button("Analyze symptoms")

                with gr.Column():
                    tips_output = gr.Textbox(label="possible conditions & recommendation", lines=20)

            predict_btn.click(disease_prediction, inputs=keywords_input, outputs=tips_output)

        with gr.TabItem("treatment plans"):
            with gr.Row():
                with gr.Column():
                    pdf_upload = gr.File(label="Upload Policy PDF", file_types=[".pdf"])
                    policy_text_input = gr.Textbox(
                        label="medical condition",
                        placeholder="e.g., diabetes,hypertension, migraine...",
                        lines=2
                    )
                    plan_btn = gr.Button("generate treatment plan")

                with gr.Column():
                     plan_output = gr.Textbox(label="Personalized treatment plan", lines=20)

            plan_btn.click(policy_summarization, inputs=[pdf_upload, policy_text_input], outputs=plan_output)

app.launch(share=True)

